my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path("users/", include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/quotes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main,  name='main'),
    path('quotes/', views.quotes, name='quotes'),
    path('authors/', views.authors, name='authors'),
    path('about/<int:author_id>', views.about, name='about'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('t_quotes/<int:tag_id>', views.t_quotes, name='t_quotes'),
]

my_site/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(),
         name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

my_site/quotes/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False)
    born_date = models.DateField()
    born_location = models.CharField(max_length=3000, default='No data')
    description = models.CharField(max_length=10000, default='No data')

    def __str__(self):
        return f"{self.fullname}"


class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    # def __str__(self):
    #     return f"{self.name}"


class Note(models.Model):
    text = models.CharField(max_length=2000, null=False)
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.text}"

my_site/quotes/forms.py
from django.forms import ModelForm, CharField, DateField, TextInput, DateInput

from . models import Author, Note


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_date = DateField(widget=DateInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=3000, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(max_length=10000, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    text = CharField(max_length=10000, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Note
        fields = ['text']
        exclude = ['author', 'tags']

my_site/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.core.paginator import Paginator
from django.conf import settings

from .forms import AuthorForm, QuoteForm
from .models import Author, Note, Tag


# Create your views here.

def main(request):
    return render(request, 'quotes/base.html', context={"title": "MY_site"})


def quotes(request):
    quotes = Note.objects.all()
    paginator = Paginator(quotes, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    top = Note.objects.all().values('tags').annotate(total=Count('text')).order_by('-total')[:10]
    top_tags = {}
    for tg in top:
        tag = Tag.objects.filter(pk=tg['tags']).get()
        top_tags[tag] = tg['total']
    # print(top_tags)
    return render(request, 'quotes/quotes.html',
                  context={"title": "MY_site/Q", "quotes": quotes, "top_tags": top_tags, 'page_obj': page_obj})


def authors(request):
    authors = Author.objects.all()
    paginator = Paginator(authors, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'quotes/authors.html',
                  context={"title": "MY_site/A", "authors": authors, 'page_obj': page_obj})


@login_required
def add_author(request):
    form = AuthorForm(instance=Author())
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            pic = form.save()
            pic.save()
            return redirect(to="quotes:authors")
    return render(request, 'quotes/add_author.html', context={"form": form})


@login_required
def add_quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()
    form = QuoteForm(instance=Note())

    if request.method == "POST":
        form = QuoteForm(request.POST, instance=Note())
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.author = Author.objects.get(fullname=request.POST.get('author'))
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quotes:quotes")
        else:
            return render(request, 'quotes/add_quote.html', {"tags": tags, "authors": authors, 'form': form})
    return render(request, 'quotes/add_quote.html', context={"tags": tags, "authors": authors, 'form': form})


def about(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/about.html', context={'author': author})


def t_quotes(request, tag_id):
    t_quotes = Note.objects.filter(tags=tag_id)
    tg = Tag.objects.filter(pk=tag_id).get()

    return render(request, 'quotes/t_quotes.html', context={'t_quotes': t_quotes, 'tg': tg})

my_site/quotes/templates/quotes/about.html
{% extends "quotes/base.html" %}

{% block content %}
<a href="{% url 'quotes:add_author' %}" class="btn btn-outline-primary btn-lg" style="color: #980B92"  type="button">ADD Author</a>

<div class="container py-4">
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 bg-body-tertiary border rounded-3">
                <h2>{{author.fullname}}</h2>
                <p>{{author.born_date}}</p>
                <p>{{author.born_location}}</p>
                <p>{{author.description}}</p>
            </div>
        </div>
    </div>

</div>

{% endblock %}

my_site/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}


{% block content %}
<h3>Please provide complete and trusty information about the author</h3>
<form action="{% url 'quotes:add_author' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Fullname</label>
        {{form.fullname}}
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Birthday</label>
        {{form.born_date}}
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Born Location</label>
        {{form.born_location}}
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div class="mb-3">
        <label class="form-label">Description</label>
        {{form.description}}
        <span>{{ form.errors.description }}</span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

my_site/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}


{% block content %}
<h2>Add Quote</h2>
<form action="{% url 'quotes:add_quote' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <label> Select Author:
        <select name="author" required>
            {% for author in authors %}
            <option value="{{author.fullname}}">{{author.fullname}}</option>
            {% endfor %}
        </select>
    </label>
    <div class="mb-3">
        <label class="form-label">Text</label>
        {{form.text}}
        <span>{{ form.errors.text}}</span>
    </div>
    <label> Select tags:
        <select name="tags" multiple="multiple" required>
            {% for tag in tags %}
            <option value="{{tag.name}}">{{tag.name}}</option>
            {% endfor %}
        </select>
    </label>
    <h4></h4>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

my_site/quotes/templates/quotes/authors.html
{% extends "quotes/base.html" %}

{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'quotes:add_author' %}" class="btn btn-outline-primary btn-lg" style="color: #980B92" type="button">ADD
    Author</a>
{% endif %}


<div class="container py-4">
    {% for author in page_obj %}
    <div class="row align-items-md-stretch">
        <div class="col-md-10">
            <div class="h-100 p-5 bg-body-tertiary border rounded-3">
                <h2><a href="{% url 'quotes:about' author.id %}">{{author.fullname}}</a></h2>
                <p>{{author.born_date}}</p>
                <p>{{author.born_location}}</p>
                <p>{{author.description}}</p>
            </div>
        </div>
    </div>
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
</div>

{% endblock %}

my_site/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<style> a { color: maroon; text-decoration: none; } a:hover { border-bottom: 4px double blue; } </style>
<body>
<div class="container">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-light text-dark" role="button">{{user.username}}</a>
        <a class="btn btn-outline-secondary" href="{% url 'users:logout' %}" role="button">LogOut</a>
        {% else %}
        <a class="btn btn-outline-secondary" href="{% url 'users:login' %}" role="button">SignIn</a>
        <a class="btn btn-outline-secondary" href="{% url 'users:register' %}" role="button">SignUp</a>
        {% endif %}
    </div>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" style="color: #980B92" aria-current="page" href="{% url 'quotes:quotes' %}">Quotes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" style="color: #980B92" href="{% url 'quotes:authors' %}">Authors</a>


    </ul>
    {% block content %}
    {% endblock %}
</div>

</body>
<footer class="pt-3 mt-4 text-body-secondary border-top">
    <div class="container">
        <p class="text-muted">
            Quotes by: <a href="https://www.facebook.com/anton.golovin.12" target="_blank">Anton Holovin</a>
        </p>
        <p class="copyright">
            Made with <a href="https://goit.global/ua/" target="_blank">GoIT</a>
        </p>
    </div>
</footer>
</html>

my_site/quotes/templates/quotes/body.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <title>Jumbotron example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/jumbotron/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Jumbotron example</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-body-secondary border-top">
      &copy; 2023
    </footer>
  </div>
</main>


    
  </body>
</html>

my_site/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}
{% endblock %}

my_site/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}
{% load extract_tags %}

{% block content %}
<!--<div class="blockquote"></div>-->
{% if user.is_authenticated %}
<a href="{% url 'quotes:add_quote' %}" class="btn btn-outline-primary btn-lg" style="color: #980B92" type="button">ADD
    Quote</a>
{% endif %}

<div class="container py-4">
    <div class="row justify-content-start">
        <div class="col-11">
            {% for quote in page_obj %}
            <div class="row align-items-md-stretch">
                <div class="col-md-10">
                    <div class="h-100 p-5 bg-body-tertiary border rounded-3">
                        <h2><a href="{% url 'quotes:about' quote.author.id %}">{{quote.author}}</a></h2>
                        <p>{{quote.text}}</p>
                        <p>Tags: <small>
                            {% for tag in quote.tags|tags %}
                            <a href="{% url 'quotes:t_quotes' tag.id %}" style="border-bottom:  none ;">{{ tag.name }},</a>
                            {% endfor %}
                        </small></p>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div>
        <div class="col-1">
            {% for top_tag in top_tags %}
            <h2><a href="{% url 'quotes:t_quotes' top_tag.id %}" style="color: red">{{top_tag.name}}</a></h2>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

my_site/quotes/templates/quotes/t_quotes.html
{% extends "quotes/base.html" %}
{% load extract_tags %}

{% block content %}

<div class="container py-4">
    <h2>Your quotes for tag: {{ tg.name }}</h2>
    {% for quote in t_quotes %}
    <div class="row align-items-md-stretch">
        <div class="col-md-10">
            <div class="h-100 p-5 bg-body-tertiary border rounded-3">
                <h2><a href="{% url 'quotes:about' quote.author.id %}">{{quote.author}}</a></h2>
                <p>{{quote.text}}</p>
                <p>Tags: <small>
                    {% for tag in quote.tags|tags %}
                    <a href="{% url 'quotes:t_quotes' tag.id %}" style="border-bottom:  none ;">{{ tag.name }},</a>
                    {% endfor %}
                </small></p>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}